-- Actions a tool proposed but that only run after the user confirms them.
-- The agent cannot confirm: confirmation comes from the interface, and code then
-- runs the stored call without the model.

CREATE TABLE core_pending_actions (
  id INTEGER PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  module TEXT NOT NULL,
  tool TEXT NOT NULL,
  arguments TEXT NOT NULL,   -- JSON, as sent by the model; validated again before running
  summary TEXT NOT NULL,     -- human-readable description, generated by code
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'done', 'rejected', 'failed', 'expired')),
  resolved_at TIMESTAMP,
  result TEXT
);
CREATE INDEX core_pending_actions_status ON core_pending_actions (status, created_at);

CREATE TRIGGER core_pending_actions_no_delete BEFORE DELETE ON core_pending_actions
BEGIN SELECT RAISE(ABORT, 'rows are never deleted; archive them instead'); END;
